model_class_names = {
    "animals": "animals",
    "branding": "branding and advertisements",
    "devotional": "devotional",
    "education": "education",
    "entertainment": "entertainment",
    "family-and-friends": "family and friends",
    "music": "music and singing",
    "health": "health and fitness",
    "shopping": "shopping",
    "home-decoration": "home decoration",
    "fashion": "fashion",
    "inspirational": "inspirational",
    "automobiles": "automobiles",
    "sports-and-games": "sports and games",
    "adventure": "adventure",
    "art-and-creativity": "art and creativity",
    "animation": "animation",
    "gaming": "gaming",
    "dance": "dance",
    "beauty-and-grooming": "beauty and grooming",
    "gadgets-and-technology": "gadgets and technology",
    "selfies": "selfies",
    "animal-cruelty": "animal cruelty",
    "dead-bodies-and-corpes": "dead bodies and corpes",
    "physical-violence": "physical violence",
    "visually-disturbing": "visually disturbing",
    "weapons-and-firearms": "weapons and firearms",
    "national-asset": "national asset",
    "politics": "politics",
    "problematic-content": "problematic content",
    "news": "news",
    "self-harm": "self-harm and suicide",
    "recipe": "recipe",
    "street-food": "street food",
    "beverages": "beverages",
    "desserts": "desserts",
    "beach": "beach",
    "nature": "nature",
    "travel-vlogs": "travel vlogs",
    "anniversary": "anniversary",
    "celebration-and-wishes": "celebratory wishes",
    "instruments": "instruments",
    "monuments": "monuments",
    "amusement-park": "amusement park",
    "travel-accomodation": "travel accomodation and hotels",
    "music-celebrities": "music celebrities",
}

coop_classnames = [
    "animals",
    "branding and advertisements",
    "devotional",
    "education",
    "entertainment",
    "family and friends",
    "music and singing",
    "health and fitness",
    "shopping",
    "home decoration",
    "fashion",
    "inspirational",
    "automobiles",
    "sports and games",
    "adventure",
    "art and creativity",
    "animation",
    "gaming",
    "dance",
    "beauty and grooming",
    "gadgets and technology",
    "selfies",
    "animal cruelty",
    "dead bodies and corpes",
    "physical violence",
    "visually disturbing",
    "weapons and firearms",
    "national asset",
    "politics",
    "problematic content",
    "news",
    "self-harm and suicide",
    "recipe",
    "street food",
    "beverages",
    "desserts",
    "beach",
    "nature",
    "travel vlogs",
    "anniversary",
    "celebratory wishes",
    "instruments",
    "monuments",
    "amusement park",
    "travel accomodation and hotels",
    "music celebrities",
]

model_class_index_to_eval_category = {
    0: "animals",
    1: "branding",
    2: "devotional",
    3: "education",
    4: "entertainment",
    5: "family-and-friends",
    6: "music",
    7: "health",
    8: "life-style",
    9: "life-style",
    10: "life-style",
    11: "inspirational",
    12: "automobiles",
    13: "sports-and-games",
    14: "adventure",
    15: "art-and-creativity",
    16: "animation",
    17: "gaming",
    18: "dance",
    19: "beauty-and-grooming",
    20: "gadgets-and-technology",
    21: "selfies",
    22: "animal-cruelty",
    23: "dead-bodies-&-corpes",
    24: "physical-violence",
    25: "visually-disturbing",
    26: "weapons-&-firearms",
    27: "national-asset",
    28: "politics",
    29: "problematic-content",
    30: "news",
    31: "self-harm",
    32: "recipe",
    33: "street-food",
    34: "beverages",
    35: "desserts",
    36: "beach",
    37: "nature",
    38: "travel-vlogs",
    39: "celebration-and-wishes",
    40: "celebration-and-wishes",
    41: "instruments",
    42: "monuments",
    43: "amusement-park",
    44: "travel-accomodation",
    45: "music-celebrities",
}


eval_category_to_lomotif_pri_category = {
    "animals": "animals",
    "branding": "branding",
    "devotional": "devotional",
    "education": "education",
    "entertainment": "entertainment",
    "family-and-friends": "family-and-friends",
    "music": "music",
    "health": "health",
    "life-style": "life-style",
    "inspirational": "inspirational",
    "automobiles": "automobiles",
    "sports-and-games": "sports-and-games",
    "adventure": "adventure",
    "art-and-creativity": "art-and-creativity",
    "animation": "animation",
    "gaming": "gaming",
    "dance": "dance",
    "beauty-and-grooming": "beauty-and-grooming",
    "gadgets-and-technology": "gadgets-and-technology",
    "selfies": "selfies",
    "animal-cruelty": "violence",
    "dead-bodies-&-corpes": "violence",
    "physical-violence": "violence",
    "visually-disturbing": "violence",
    "weapons-&-firearms": "violence",
    "national-asset": "national-asset",
    "politics": "politics",
    "problematic-content": "problematic-content",
    "news": "news",
    "self-harm": "harmful-acts",
    "recipe": "food",
    "street-food": "food",
    "beverages": "food",
    "desserts": "food",
    "beach": "travel",
    "nature": "travel",
    "travel-vlogs": "travel",
    "celebration-and-wishes": "celebration-and-wishes",
    "instruments": "music",
    "monuments": "travel",
    "amusement-park": "travel",
    "travel-accomodation": "travel",
    "music-celebrities": "music",
}

primary_category_dict = {
    "animals": ["birds", "domestic-animals", "pets", "wild-life", "sea-animals"],
    "branding": ["advertisement"],
    "devotional": ["religious-speech", "religious-festivals", "god", "holy-places"],
    "education": ["tutorials", "general-knowledge", "quiz", "science-facts"],
    "entertainment": [
        "performance",
        # "comedy",
        # "drama",
        # "meme",
        # "bloopers",
        # "funny-clips",
        # "challenges",
        # "funny-dubbing",
        # "fun-quiz",
        # "pranks",
        "romantic",
        # "entertainment-celebrities",
        "party",
        "tv-series-and-shows",
        "movie",
        "interviews",
        "content-reviews",
        "patriotic",
        "magic-shows",
        # "magic-tricks",
        "music-performance",
        "singing",
    ],
    "family-and-friends": ["kids", "friends", "family"],
    "recipe": ["recipe", "food-items"],
    "street-food": ["street-food", "food-items"],
    "beverages": ["beverages"],
    "desserts": ["desserts"],
    # "food-diy": ["food-diy"],
    # "food": ["recipe", "street-food", "food-celebrities", "beverages", "desserts"],
    "health": ["fitness", "health-tips", "mental-health", "wellness", "yoga", "spa"],
    "life-style": ["shopping", "home-decor", "fashion", "celebrities-lifestyle"],
    "inspirational": [
        "quotes",
        "attitude-motivation",
        "spiritual-motivation",
        "motivational-celebrities",
        "life-hacks-advice",
    ],
    "automobiles": ["car", "motorbikes", "trucks", "aeroplane", "train", "bus", "boat"],
    "sports-and-games": [
        "cricket",
        "badminton",
        "football",
        "wrestling",
        "hockey",
        "basketball",
        "boxing",
        "racing",
        "swimming",
        "sports-celebrities",
        "bull-riding",
        "tennis",
        "kabadi",
        "indoor-games",
        "boardgames",
        "sports-tournament",
        "other-sports",
        "amusement-park",
    ],
    "adventure": [
        "skateboarding",
        "sky-diving",
        "bungee-jump",
        "wing-suit",
        "rope-walking",
        "adventure-rides",
        "vehicular-stunts",
        "surfing",
        "parkour",
        "other-stunts",
        "climbing-and-hiking",
        "watersports",
    ],
    "art-and-creativity": [
        "photography",
        "drawing-and-painting",
        "pottery",
        "sculpture",
        "other-crafts",
    ],
    "beach": ["beach"],
    "nature": ["nature"],
    "travel-vlogs": ["travel-vlogs"],
    "amusement-park": ["amusement-park"],
    "monuments": ["monuments"],
    # "birthday": ["birthday"],
    # "other-wishes": ["other-wishes"],
    "anniversary": ["anniversary"],
    # "special-days": ["special-days"],
    "celebration-and-wishes": [
        "birthday",
        "other-wishes",
        "anniversary",
        "special-and-festival-days",
    ],
    "instruments": ["instruments"],
    "music-celebrities": ["music-celebrities"],
    "music": ["music-performance", "singing", "music-reviews"],
    "animation": ["anime", "cartoon"],
    "gaming": ["other-gaming", "virtual-gaming"],
    "dance": ["dancing", "dance-performance", "dance-parties"],
    "beauty-and-grooming": [
        "make-up",
        "skincare",
        "hair",
        "grooming-tips",
        "nails",
        "beauty-accessories",
    ],
    "gadgets-and-technology": [
        "mobile-phones",
        "watches",
        "audio",
        "home-theatre",
        "lifestyle-gadgets",
        "gadget-tips",
        "tech-news",
        "tech-reviews",
        "cameras",
        "computers-and-laptops",
        "tablets",
        "electronic-accessories",
    ],
    "selfies": ["selfie"],
    "physical-violence": [
        "physical-violence",
    ],
    "visually-disturbing": ["visually-disturbing"],
    "dead-bodies-&-corpes": ["dead-bodies-&-corpes"],
    "animal-cruelty": ["animal-cruelty"],
    "weapons-&-firearms": ["weapons-&-firearms"],
    "national-asset": ["national-asset"],
    "politics": ["politics"],
    "problematic-content": ["problematic-content"],
    "news": ["news"],
    # "drugs-tobacco-alcohol": ["drugs-tobacco-alcohol"],
    # "dangerous-stunts": ["dangerous-stunts"],
    "self-harm": ["self-harm", "suicide"],
    "travel-accomodation": ["travel-accomodation"],
    # "poor-quality-video": ["poor-quality-video"]
    # "violence": [
    #     "profanity",
    #     "physical-violence",
    #     "visually-disturbing",
    #     "riots",
    #     "dead-bodies-&-corpes",
    #     "animal-cruelty",
    #     "weapons-&-firearms",
    # ],
    # "nudity-&-sexual": [
    #     "sexually-suggestive",
    #     "explicit-nudity",
    #     "partial-nudity",
    #     "revealing-clothes",
    #     "sexual-activity",
    #     "pornography",
    # ],
}

sec_cat_descriptions_dict = {
    "birds": "This is a photo of an animal , a type of bird",
    "domestic-animals": "This is a photo of an animal , a type of domestic animal such as goats sheeps cows on a farm",
    "pets": "This is a photo of an animal , someone's pet like dogs cats rabbits and other pets",
    "wild-life": "This is a photo of an animal , a type of animal that is found in the wild like tigers snakes",
    "sea-animals": "This is a photo of an animal , a type of sea animal",
    "advertisement": "This is a photo of a branding , a type of advertisement",
    "religious-speech": "This is a photo of a devotional activity , a person giving religious speech",
    "religious-festivals": "This is a photo of a devotional activity , a type of religious or holy celebration",
    "god": "This is a photo of a devotional category , either image or statue of god or god worship",
    "holy-places": "This is a photo of a devotional category , a holy place of worship",
    "tutorials": "This is a photo belonging to educational category, related to tutorials",
    "general-knowledge": "This is a photo belonging to educational category, which imparts general-knowledge",
    "quiz": "This is a photo belonging to educational category, related to quiz",
    "science-facts": "This is a photo belonging to educational category, related to science facts and science topics",
    "performance": "This is a photo belonging to an entertainment category , where a person is performing on stage with an audience",
    # "comedy": "This is a photo belonging to an entertainment category , related to comedy",
    # "drama": "This is a photo belonging to an entertainment category , related to drama",
    # "meme": "This is a photo belonging to an entertainment category , related to memes",
    # "bloopers": "This is a photo belonging to an entertainment category , related to bloopers",
    # "funny-clips": "This is a photo belonging to an entertainment category , related to funny-clips",
    # "funny-dubbing": "This is a photo belonging to an entertainment category , related to funny-dubbing",
    # "pranks": "This is a photo belonging to an entertainment category , related to pranks",
    "romantic": "This is a photo of a lovely couple or about romantic relationships",
    "entertainment-celebrities": "This is a photo of a celebrity",
    "party": "This is a photo of party celebration or party decoration such as balloons and confetti",
    "tv-series-and-shows": "This is a photo belonging to an entertainment category , related to tv series and shows",
    "movie": "This is a photo belonging to an entertainment category , related to a movie",
    "interviews": "This is a photo belonging to an entertainment category , related to interviews",
    "content-reviews": "This is a photo belonging to an entertainment category , related to a tv or movie review",
    "patriotic": "This is a photo belonging to an entertainment category , related facts about a country, national anthem or patriotism",
    "magic-shows": "This is a photo belonging to an entertainment category , related to magic shows on a stage with an audience",
    "magic-tricks": "This is a photo showing magic tricks",
    "kids": "This is a photo of parents and their children or babies",
    "family": "This is a family photo",
    "friends": "This is a photo of a group of people or friends",
    "recipe": "This is a photo related to food , a recipe to prepare the dish",
    "street-food": "This is a photo of some street-food",
    "food-items": "This is a photo related to food dishes and ingredients",
    "food-celebrities": "This is a photo related to food , a celebrity along with food",
    "beverages": "This is a photo related to food , a type of beverage",
    "desserts": "This is a photo related to food , a type of dessert or sweets",
    "fitness": "This is a photo related to health fitness, where people are exercising",
    "health-tips": "This is a photo related to health-fitness, about health tips",
    "mental-health": "This is a photo related to health-fitness, about mental health awareness",
    "yoga": "This is a photo related to health-fitness, particularly yoga activities",
    "spa": "This is a photo related to health-fitness, particularly about spa treatments",
    "shopping": "This is a photo related to life-style , particularly to shopping",
    "home-decor": "This is a photo related to life-style , specifically to home decor",
    "fashion": "This is a photo related to life-style , particularly to fashion",
    "home-diy": "This is a photo related to life-style , particularly to home diy or home hacks",
    "celebrities-lifestyle": "This is a photo related to life-style , particularly to celebrities lifestyle",
    "quotes": "This is a photo belonging to motivational category with quotes",
    "attitude-motivation": "This is a photo belonging to motivational category , a type of attitude-motivation",
    "spiritual-motivation": "This is a photo belonging to motivational category , a type of spiritual-motivation",
    "motivational-celebrities": "This is a photo belonging to motivational category which involves a celebrity",
    "life-hacks-advice": "This is a photo belonging to motivational category which gives advice on leading a better life",
    "car": "This is a photo belonging to automobiles , which has a car",
    "motorbikes": "This is a photo belonging to automobiles , which has a motorbike",
    "trucks": "This is a photo belonging to automobiles , which has trucks",
     "aeroplane": "This is a photo belonging to automobiles , which has aeroplane",
    "boat": "This is a photo belonging to automobiles , which has boat",
    "train": "This is a photo belonging to automobiles , which has train",
    "bus": "This is a photo belonging to automobiles, which has a coach, van or bus",
    "automobile-hacks": "This is a photo belonging to automobiles , which gives automobile tips and hacks",
    "cricket": "This is a photo of sports, particularly cricket",
    "badminton": "This is a photo of sports, particularly badminton",
    "football": "This is a photo of sports, particularly football",
    "wrestling": "This is a photo of sports, particularly wrestling",
    "hockey": "This is a photo of sports, particularly hockey",
    "basketball": "This is a photo of sports, particularly basketball",
    "boxing": "This is a photo of sports, particularly boxing",
    "racing": "This is a photo of sports, particularly racing",
    "swimming": "This is a photo of sports, particularly swimming",
    "sports-celebrities": "This is a photo of sports, which includes an sports celebrity",
    "bull-riding": "This is a photo of sports, particularly bull-riding",
    "tennis": "This is a photo of sports, particularly tennis",
    "kabadi": "This is a photo of sports, particularly kabadi",
    "indoor-games": "This is a photo of indoor sports",
    "boardgames": "This is a photo of sports, particularly board games",
    "sports-tournament": "This is a photo of sports, particularly sports tournaments, competitions and olympics",
    "other-sports": "This is a photo of sports, particularly other sports",
    "skateboarding": "This is a photo related to stunts-&-adventures , particularly ",
    "sky-diving": "This is a photo related to stunts-&-adventures , particularly ",
    "bungee-jump": "This is a photo related to stunts-&-adventures , particularly to bungee-jump",
    "wing-suit": "This is a photo related to stunts-&-adventures , particularly to wing-suit",
    "rope-walking": "This is a photo related to stunts-&-adventures , particularly to rope-walking",
    "adventure-rides": "This is a photo related to stunts-&-adventures , particularly to adventure-rides",
    "vehicular-stunts": "This is a photo related to stunts-&-adventures , particularly to vehicular-stunts",
    "surfing": "This is a photo related to stunts-&-adventures , particularly to surfing",
    "parkour": "This is a photo related to stunts-&-adventures , particularly to parkour",
    "other-stunts": "This is a photo related to stunts-&-adventures , particularly to other stunts",
    "climbing-and-hiking": "This is a photo related to stunts-&-adventures , particularly to climbing and hiking",
    "watersports": "This is a photo related to stunts-&-adventures , particularly to watersports",
    "photography": "This is a photo belonging to art and creativity category , particularly to photography",
    "drawing-and-painting"
    "pottery": "This is a photo belonging to art and creativity category , particularly to pottery",
    "sculpture": "This is a photo belonging to art and creativity category , particularly to sculptures",
    "other-crafts": "This is a photo belonging to art and creativity category , particularly to other crafts",
    "beach": "This is a photo related to travel, particularly to beaches",
    "nature": "This is a photo of related to travel and nature , particularly to scenes taken from aircraft, trees and nature",
    "travel-accomodation": "This is a photo of related to travel, particularly about hotels, rooms and lodging",
    "travel-vlogs": "This is a photo related to travel, particularly to travel vlogs",
    "birthday": "This is a photo related to birthday parties, birthday cakes, birthday messages such as HPBD or happy birthday or feliz Aniversário, birthday balloons",
    "other-wishes": "This is a photo related to celebrations or wishes , particularly for other-wishes",
    "anniversary": "This is a photo related to celebrations or wishes , particularly for romantic anniversary or happy anniversary",
    # "special-days": "This is a photo related to celebrations or wishes , particularly for special-days",
    "special-and-festival-days": "This is a photo related to festivals and festivities, like christmas, ramadan, diwali or friendship day",
    "music-performance": "This is a photo of someone singing at a music concert on a stage with an audience",
    "singing": "This is a photo of someone singing some song tracks to the camera or showing music",
    "instruments": "This is a photo related to music, where a person is playing some musical instruments",
    "music-celebrities": "This is a photo related to music, about music celebrities",
    "music-reviews": "This is a photo related to music, particularly reviews about a music or song",
    "anime": "This is a photo of some anime characters",
    "gifs": "This is a photo related to animation, particularly for gifs",
    "cartoon": "This is a photo of some cartoon characters",
    "other-gaming": "This is a photo related to gaming, particularly on other gaming",
    "virtual-gaming": "This is a photo related to gaming, particularly for virtual games or computer games",
    "dancing": "This is a photo related to dance, particularly one person dancing or showing dance steps",
    "dance-performance": "This is a photo related to dance, particularly a person giving a dance performance on a stage with an audience",
    "dance-parties": "This is a photo related to dance, particularly a group of people dancing or partying",
    "make-up": "This is a photo related to beauty-and-grooming, make-up, cosmetics, or someone with heavy make-up",
    "skincare": "This is a photo related to beauty-and-grooming, particularly to skincare and facial",
    "hair": "This is a photo related to beauty-and-grooming, particularly to hair, hair styling, hair services",
    "grooming-tips": "This is a photo of a man who is grooming himself or giving grooming tips",
    "nails": "This is a photo related to beauty-and-grooming, particularly to nails",
    "beauty-accessories": "This is a photo related to beauty-and-grooming, particularly to beauty accessories",
    "mobile-phones": "This is a photo of a smartphone, like iPhone",
    "watches": "This is a photo related to gadgets and technology, particularly to watches",
    "audio": "This is a photo related to gadgets and technology, particularly to audio devices such as headset, earphones and microphones",
    "home-theatre": "This is a photo related to gadgets and technology, particularly to home theatre such as soundbars and television",
    "lifestyle-gadgets": "This is a photo related to gadgets and technology, particularly to other lifestyle gadgets",
    "gadget-tips": "This is a photo related to gadgets and technology, particularly to gadget tips",
    "tech-news": "This is a photo related to gadgets and technology, particularly to tech news",
    "tech-reviews": "This is a photo related to gadgets and technology, particularly to tech reviews",
    "cameras": "This is a photo related to gadgets and technology, particularly to cameras",
    "computers-and-laptops": "This is a photo related to gadgets and technology, particularly to computers and laptops",
    "tablets": "This is a photo related to gadgets and technology, particularly to tablets",
    "electronic-accessories": "This is a photo related to gadgets and technology, particularly to other electronics accessories",
    "selfie": "This is a selfie, a photograph or portrait of one person",
    # "profanity": "This is a photo where a person is being obscene or offensive",
    "physical-violence": "This is a photo showing physical violence and acts of physical assault",
    "visually-disturbing": "This is a photo related to violence, and is visully disturbing",
    # "riots": "This is a photo related to violence, particularly belonging to riots",
    "dead-bodies-&-corpes": "This is a photo related to violence, where dead bodies and corpes are seen",
    "animal-cruelty": "This is a photo related to violence, particularly belonging to animal cruelty",
    "weapons-&-firearms": "This is a photo where a weapon is seen or a person is carrying weapon, hence belongs to nsfw",
    # "sexually-suggestive": "This is a photo related to nudity and sexual, particularly sexually suggestive",
    # "explicit-nudity": "This is a photo related to nudity and sexual, particularly belonging to explicit nudity",
    # "partial-nudity": "This is a photo related to nudity and sexual, particularly belonging to partial nudity",
    # "revealing-clothes": "This is a photo related to nudity and sexual, where the person is wearing revealing clothes",
    # "sexual-activity": "This is a photo related to nudity and sexual, particularly belonging to sexual activity",
    # "pornography": "This is a photo related to nudity and sexual, particularly belonging to pornography",
    "food-diy": "This is a photo about food hacks and cooking tips",
    "wellness": "This is a photo giving tips on healthy lifestyle and wellness",
    "drawing-and-painting": "This is a photo about drawing and painting",
    "pottery": "This is a photo about pottery or ceramics",
    "amusement-park": "This is a photo at amusement parks or water parks",
    "monuments": "This is a photo about monuments and travel",
    "national-asset": "This is a photo about national content or national flags",
    "politics": "This is a photo about politics",
    "problematic-content": "This is a photo about some problematic content",
    "news": "This is a photo about news",
    "self-harm": "This is a photo displaying self-harm",
    "suicide": "This is a photo about suicide or suicidal acts",
}

sec_to_pri_cat = {
    "birds": "animals",
    "domestic-animals": "animals",
    "pets": "animals",
    "wild-life": "animals",
    "sea-animals": "animals",
    "advertisement": "branding",
    "religious-speech": "devotional",
    "religious-festivals": "devotional",
    "god": "devotional",
    "holy-places": "devotional",
    "tutorials": "education",
    "general-knowledge": "education",
    "quiz": "education",
    "science-facts": "education",
    "performance": "entertainment",
    "romantic": "entertainment",
    "party": "entertainment",
    "tv-series-and-shows": "entertainment",
    "movie": "entertainment",
    "interviews": "entertainment",
    "content-reviews": "entertainment",
    "patriotic": "entertainment",
    "magic-shows": "entertainment",
    "music-performance": "music",
    "singing": "music",
    "kids": "family-and-friends",
    "friends": "family-and-friends",
    'family': 'family-and-friends',
    "recipe": "food",
    "street-food": "food",
    'food-items': 'food',
    "beverages": "food",
    "desserts": "food",
    "fitness": "health",
    "health-tips": "health",
    "mental-health": "health",
    "wellness": "health",
    "yoga": "health",
    "spa": "health",
    "shopping": "life-style",
    "home-decor": "life-style",
    "fashion": "life-style",
    "celebrities-lifestyle": "life-style",
    "quotes": "inspirational",
    "attitude-motivation": "inspirational",
    "spiritual-motivation": "inspirational",
    "motivational-celebrities": "inspirational",
    "life-hacks-advice": "inspirational",
    "car": "automobiles",
    "motorbikes": "automobiles",
    "trucks": "automobiles",
    'aeroplane': 'automobiles',
    'train': 'automobiles',
    'boat': 'automobiles',
    'bus': 'automobiles',
    "cricket": "sports-and-games",
    "badminton": "sports-and-games",
    "football": "sports-and-games",
    "wrestling": "sports-and-games",
    "hockey": "sports-and-games",
    "basketball": "sports-and-games",
    "boxing": "sports-and-games",
    "racing": "sports-and-games",
    "swimming": "sports-and-games",
    "sports-celebrities": "sports-and-games",
    "bull-riding": "sports-and-games",
    "tennis": "sports-and-games",
    "kabadi": "sports-and-games",
    "indoor-games": "sports-and-games",
    "boardgames": "sports-and-games",
    "sports-tournament": "sports-and-games",
    "other-sports": "sports-and-games",
    "amusement-park": "amusement-park",
    "skateboarding": "adventure",
    "sky-diving": "adventure",
    "bungee-jump": "adventure",
    "wing-suit": "adventure",
    "rope-walking": "adventure",
    "adventure-rides": "adventure",
    "vehicular-stunts": "adventure",
    "surfing": "adventure",
    "parkour": "adventure",
    "other-stunts": "adventure",
    "climbing-and-hiking": "adventure",
    "watersports": "adventure",
    "photography": "art-and-creativity",
    "drawing-and-painting": "art-and-creativity",
    "pottery": "art-and-creativity",
    "sculpture": "art-and-creativity",
    "other-crafts": "art-and-creativity",
    "beach": "travel",
    "nature": "travel",
    "travel-vlogs": "travel",
    "monuments": "travel",
    "anniversary": "celebration-and-wishes",
    "birthday": "celebration-and-wishes",
    "other-wishes": "celebration-and-wishes",
    #  'special-days': 'celebration-and-wishes',
    'special-and-festival-days': 'celebration-and-wishes',
    "instruments": "music",
    "music-celebrities": "music",
    "music-reviews": "music",
    "anime": "animation",
    "cartoon": "animation",
    "other-gaming": "gaming",
    "virtual-gaming": "gaming",
    "dancing": "dance",
    "dance-performance": "dance",
    "dance-parties": "dance",
    "make-up": "beauty-and-grooming",
    "skincare": "beauty-and-grooming",
    "hair": "beauty-and-grooming",
    "grooming-tips": "beauty-and-grooming",
    "nails": "beauty-and-grooming",
    "beauty-accessories": "beauty-and-grooming",
    "mobile-phones": "gadgets-and-technology",
    "watches": "gadgets-and-technology",
    "audio": "gadgets-and-technology",
    "home-theatre": "gadgets-and-technology",
    "lifestyle-gadgets": "gadgets-and-technology",
    "gadget-tips": "gadgets-and-technology",
    "tech-news": "gadgets-and-technology",
    "tech-reviews": "gadgets-and-technology",
    "cameras": "gadgets-and-technology",
    "computers-and-laptops": "gadgets-and-technology",
    "tablets": "gadgets-and-technology",
    "electronic-accessories": "gadgets-and-technology",
    "selfie": "selfies",
    "physical-violence": "violence",
    "visually-disturbing": "violence",
    "dead-bodies-&-corpes": "violence",
    "animal-cruelty": "violence",
    "weapons-&-firearms": "violence",
    "national-asset": "national-asset",
    "politics": "politics",
    "problematic-content": "problematic-content",
    "news": "news",
    "self-harm": "harmful-acts",
    "suicide": "harmful-acts",
    "travel-accomodation": "travel",
}

primary_category_dict_inv = {}
for k, v in primary_category_dict.items():
    for item in v:
        primary_category_dict_inv[item] = k
